name: Arduino Library CI

on: [pull_request, push, repository_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - uses: actions/checkout@v4
      with:
         repository: ladyada-eagleclaw/ci-arduino
         ref: main
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    - name: clang
      run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" -r .
    - name: test platforms
      run: python3 ci/build_platform.py metro_esp32p4

    - name: doxy
      env:
        GH_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PRETTYNAME: "Adafruit LT8912B Arduino Library"
      run: |
        cp ci/Doxyfile.default Doxyfile
        printf '\nPROJECT_NAME = "%s"\nPREDEFINED += ARDUINO_ARCH_ESP32=1 CONFIG_IDF_TARGET_ESP32P4=1\n' "$PRETTYNAME" >> Doxyfile
        bash ci/doxy_gen_and_deploy.sh src
